language: python
python:
  - '3.6'
install:
  - pip install --upgrade -e . -r ./requirements/dev
script:
  - pytest --cov=checkQC tests/
after_success:
  - codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: johandahlberg
  password:
    secure: XjRmFQ5libTp+iMqehiehHIaeoDfz7adlIz9YIv5+g8LWolxCtNAM8pMNE70HzrO6OhvT//ga85KOcQfPQlupNIAtPPElO0NStRMmzA1xGsAOSANdvCrGu6gyy6kxMsxmC5MVvD8sh623K/MgUg/upzojzz5yjSRAC5O72CbsjomUJH6HxrgrbsrkeBe46fRBIbgRolMCYZv1ASJaiUXTAEhwnOnfbdJJoXxcIcP3SRA1SLfYxurhOECTsLgX06V8mqzN4ieBIsTghl8VNm2qiTcnHQIs8WHY2Sq0EZuuuL5RSRTP74bDEJ8fyPNqDKU0NEgXYfExCQ0hZ68cZJ1zUvebrx778O3gj7lGRG5I0IqUzzcVjM4Rhr3FHUzFx4exTn24pZznEzylcEj5bsEN6L/dIh2bEX5N9oe/bq8TPwFE69nxTIPn4/Vju1921xH+6S5BW/vlAHLZnNaQ5SjS3M+ZBNUVf+QhwdzVF0da/KNn+DLOWjFf7ePxaXCzlV8/12cLni2RKtt5WNrRp9DCWLreqaY0fXnPFC9i8JF3zSh043Kiq4hOXavnRDAFD7+k+o3AgYmpZf6c9pla8Eb4gr2zzOeW2YJ6OHSokAayfDUZkuaBR96XbQM8Cam5dFrYrtynYGpc6Et3VT9wI4DSfcCmwNoG9jwDbQYne0z6vI=
  distributions: sdist bdist_wheel
  on:
    tags: true
