# First letter in instrument name is indicative of model
# i.e. SN7001335 is a HiSeq3500 since its name begins with
# SN
instrument_type_mappings:
  SN: hiseq2000
  M: miseq
  D: hiseq2500
  ST: hiseqx


hiseq2500_rapid:
  100-120:
    handlers:
      - name: YieldHandler
        warning: 30 # Give lowest nbr in Gbp
        error: 20 # Give lowest nbr in Gbp
      - name: UndeterminedPercentageHandler
        warning: 0.01
        error: 0.02
  121-200:
    handlers:
      - name: YieldHandler
        warning: 300 # Give lowest nbr in Gbp
        error: 200 # Give lowest nbr in Gbp
      - name: UndeterminedPercentageHandler
        warning: 0.01
        error: 0.02
miseq:
  250-300:
    handlers:
      - name: YieldHandler
        warning: 300 # Give lowest nbr in Gbp
        error: 200 # Give lowest nbr in Gbp
      - name: UndeterminedPercentageHandler
        warning: 0.01
        error: 0.02
      - name: MyNewHandler
        min: 1
        max: 3
